<?php

/**
 * @file
 * drupal_sample_module module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupal_sample_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.drupal_sample_module':
      $output = '<h3>About</h3>';
      $output .= '<p>' . t('A <b><i>hook_help</i></b> page for Hello World module.'). '</p>';
      return $output;
  }
}
